"use client";

// ── Related Studies & Articles ─────────────────────────────────────────────
// Surfaces REAL peer-reviewed articles, clinical guidelines, and meta-analyses
// from PubMed, grouped by the user's abnormal markers. Every article links to a
// live PubMed page — nothing here is generated by the LLM except the short
// relevance note (grounded strictly in the article's abstract, server-side).
//
// Generic by design: pass any { marker, value, unit, reference, status }[] and
// it works for the Lab Analyzer today and other tools (Diagnosis Explainer…)
// later. Respects the Simple/Medium/Expert complexity toggle.

import { useState } from "react";
import { useTranslations } from "next-intl";

type Tier = "simple" | "medium" | "expert";
type ArticleType = "meta-analysis" | "guideline" | "systematic-review" | "other";

interface Flag {
  marker: string;
  value: string;
  unit: string;
  reference: string;
  status: "high" | "low" | "normal";
}

interface RelatedArticle {
  pmid: string;
  title: string;
  journal: string;
  year: string | null;
  pubType: ArticleType;
  url: string;
  note?: string;
}

interface MarkerGroup {
  marker: string;
  direction: "high" | "low" | "normal";
  articles: RelatedArticle[];
}

const BADGE_STYLES: Record<ArticleType, string> = {
  "meta-analysis": "bg-indigo-50 text-indigo-700 border-indigo-200 dark:bg-indigo-900/30 dark:text-indigo-300 dark:border-indigo-800",
  guideline: "bg-emerald-50 text-emerald-700 border-emerald-200 dark:bg-emerald-900/30 dark:text-emerald-300 dark:border-emerald-800",
  "systematic-review": "bg-sky-50 text-sky-700 border-sky-200 dark:bg-sky-900/30 dark:text-sky-300 dark:border-sky-800",
  other: "bg-slate-50 text-slate-600 border-slate-200 dark:bg-slate-800 dark:text-slate-300 dark:border-slate-700",
};

export default function RelatedStudies({
  flags,
  lang,
  tier,
}: {
  flags: Flag[];
  lang: string;
  tier: Tier;
}) {
  const t = useTranslations("LabAnalyzer");
  const [open, setOpen] = useState(false);
  const [groups, setGroups] = useState<MarkerGroup[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const abnormalFlags = flags.filter((f) => f.status !== "normal");
  if (abnormalFlags.length === 0) return null;

  const badgeLabel = (type: ArticleType): string => {
    switch (type) {
      case "meta-analysis":
        return t("relatedStudiesBadgeMeta");
      case "guideline":
        return t("relatedStudiesBadgeGuideline");
      case "systematic-review":
        return t("relatedStudiesBadgeReview");
      default:
        return t("relatedStudiesBadgeOther");
    }
  };

  const fetchStudies = async () => {
    if (groups) return;
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/related-studies", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ flags: abnormalFlags, lang }),
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error || "error");
      setGroups((json.groups as MarkerGroup[]) ?? []);
    } catch {
      setError(t("relatedStudiesError"));
    } finally {
      setLoading(false);
    }
  };

  const handleToggle = () => {
    const next = !open;
    setOpen(next);
    if (next && !groups && !loading) fetchStudies();
  };

  const totalArticles = groups?.reduce((n, g) => n + g.articles.length, 0) ?? 0;

  return (
    <div className="bg-white dark:bg-slate-800 rounded-2xl border border-surface-border overflow-hidden shadow-sm print:hidden">
      {/* Header */}
      <button
        onClick={handleToggle}
        className="w-full flex items-center justify-between px-5 py-4 hover:bg-surface-raised/60 transition-colors"
      >
        <div className="flex items-center gap-2.5">
          <span className="text-base leading-none">🔬</span>
          <span className="text-sm font-semibold text-ink">{t("relatedStudiesTitle")}</span>
          <span className="hidden sm:inline-flex items-center gap-1 text-xs text-ink-tertiary border border-surface-border rounded-full px-2.5 py-0.5 bg-surface-raised ml-1">
            {open && groups
              ? `${totalArticles} ${t("relatedStudiesArticlesLabel")}`
              : t("relatedStudiesClickExplore")}
          </span>
        </div>
        <svg
          viewBox="0 0 20 20"
          fill="currentColor"
          className={`w-4 h-4 text-ink-tertiary transition-transform duration-200 flex-shrink-0 ${open ? "rotate-180" : ""}`}
        >
          <path fillRule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clipRule="evenodd" />
        </svg>
      </button>

      {open && (
        <div className="border-t border-surface-border">
          {/* Loading skeletons */}
          {loading && (
            <div className="p-5 space-y-3">
              <p className="text-sm text-ink-secondary font-medium flex items-center gap-2">
                <span className="relative w-4 h-4 inline-block">
                  <span className="absolute inset-0 border-2 border-brand-blue/20 rounded-full" />
                  <span className="absolute inset-0 border-2 border-brand-blue border-t-transparent rounded-full animate-spin" />
                </span>
                {t("relatedStudiesLoading")}
              </p>
              {[0, 1, 2].map((i) => (
                <div key={i} className="rounded-xl border border-surface-border bg-surface-raised/50 p-4 space-y-2 animate-pulse">
                  <div className="h-3.5 bg-surface-border rounded w-3/4" />
                  <div className="h-3 bg-surface-border rounded w-1/2" />
                  <div className="h-3 bg-surface-border rounded w-5/6" />
                </div>
              ))}
            </div>
          )}

          {/* Error */}
          {error && !loading && (
            <div className="p-5 space-y-3">
              <div className="flex items-start gap-2.5 p-3.5 rounded-xl bg-red-50 dark:bg-red-900/20 border border-red-100 dark:border-red-800">
                <svg viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4 text-red-500 flex-shrink-0 mt-0.5">
                  <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
                </svg>
                <p className="text-sm text-red-700 dark:text-red-400">{error}</p>
              </div>
              <button
                onClick={() => { setError(null); fetchStudies(); }}
                className="w-full py-2.5 rounded-xl border border-surface-border text-sm font-semibold text-ink-secondary hover:text-ink hover:border-brand-blue/30 hover:bg-brand-blue-light transition-all duration-150"
              >
                {t("relatedStudiesTryAgain")}
              </button>
            </div>
          )}

          {/* Empty state */}
          {groups && !loading && groups.length === 0 && (
            <div className="p-8 text-center">
              <p className="text-sm text-ink-tertiary">{t("relatedStudiesEmpty")}</p>
            </div>
          )}

          {/* Results */}
          {groups && !loading && groups.length > 0 && (
            <div className="p-5 space-y-5">
              <p className="text-xs text-ink-tertiary leading-relaxed">{t("relatedStudiesContextNote")}</p>

              {groups.map((group) => (
                <div key={`${group.marker}-${group.direction}`} className="space-y-2.5">
                  <div className="flex items-center gap-2">
                    <span className="text-[11px] font-bold text-ink-tertiary uppercase tracking-widest">
                      {group.marker}
                    </span>
                    <span className="text-[10px] text-ink-tertiary border border-surface-border rounded-full px-2 py-0.5 bg-surface-raised">
                      {group.articles.length}
                    </span>
                  </div>

                  <div className="space-y-2.5">
                    {group.articles.map((article) => (
                      <ArticleCard
                        key={article.pmid}
                        article={article}
                        tier={tier}
                        badgeLabel={badgeLabel(article.pubType)}
                        viewLabel={t("relatedStudiesViewBtn")}
                      />
                    ))}
                  </div>
                </div>
              ))}

              {/* Disclaimer */}
              <div className="flex items-start gap-2.5 px-4 py-3.5 rounded-xl bg-amber-50 dark:bg-amber-900/20 border border-amber-100 dark:border-amber-800">
                <svg viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4 text-amber-500 flex-shrink-0 mt-0.5">
                  <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                </svg>
                <p className="text-xs text-amber-700 dark:text-amber-300 leading-relaxed">
                  {t("relatedStudiesDisclaimer")}
                </p>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function ArticleCard({
  article,
  tier,
  badgeLabel,
  viewLabel,
}: {
  article: RelatedArticle;
  tier: Tier;
  badgeLabel: string;
  viewLabel: string;
}) {
  const isExpert = tier === "expert";
  const meta = [article.journal, article.year].filter(Boolean).join(" · ");

  return (
    <div className="rounded-xl border border-surface-border bg-surface-raised/50 hover:border-brand-blue/30 hover:bg-brand-blue-light/30 transition-all duration-150 overflow-hidden">
      <div className="p-4 space-y-2">
        <div className="flex items-start justify-between gap-3">
          <div className="flex-1 min-w-0">
            <span className={`inline-flex items-center text-[10px] font-semibold px-2 py-0.5 rounded-full border ${BADGE_STYLES[article.pubType]} mb-1.5`}>
              {badgeLabel}
            </span>
            <p className={`text-sm text-ink leading-snug ${isExpert ? "font-semibold" : "font-medium"}`}>
              {article.title}
            </p>
            {meta && (
              <p className={`mt-1 text-xs ${isExpert ? "text-ink-secondary font-medium" : "text-ink-tertiary"}`}>
                {meta}
              </p>
            )}
          </div>

          <a
            href={article.url}
            target="_blank"
            rel="noopener noreferrer"
            className="flex-shrink-0 inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-brand-blue hover:bg-brand-blue-hover text-white text-xs font-semibold transition-colors mt-0.5"
            aria-label={`${viewLabel} — ${article.title}`}
          >
            {viewLabel}
            <svg viewBox="0 0 16 16" fill="currentColor" className="w-3 h-3 flex-shrink-0">
              <path fillRule="evenodd" d="M4.22 11.78a.75.75 0 010-1.06l5.72-5.72H6.75a.75.75 0 010-1.5h5.5a.75.75 0 01.75.75v5.5a.75.75 0 01-1.5 0V6.06l-5.72 5.72a.75.75 0 01-1.06 0z" clipRule="evenodd" />
            </svg>
          </a>
        </div>

        {/* Relevance note — emphasised in Simple/Medium, secondary in Expert */}
        {article.note && !isExpert && (
          <p className="text-xs text-ink-secondary leading-relaxed border-l-2 border-brand-blue/30 pl-3">
            {article.note}
          </p>
        )}
        {article.note && isExpert && (
          <p className="text-[11px] text-ink-tertiary leading-relaxed italic">{article.note}</p>
        )}
      </div>
    </div>
  );
}
